# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workflows:
  version: 2

  nightly:
    jobs:
      - update_csv
    triggers:
      - schedule:
          # Every night at 4am ET
          cron: "0 9 * * *"
          filters:
            branches:
              only: master

version: 2

jobs:
  default: &default_job
    docker:
      - image: circleci/python:3.6.4
    # See sample.env file for full details
    #environment: []
        # For the following sensitive envvars, check the CircleCI UI.
        #   - DECRYPTION_PASSWORD
        #
        # See: https://circleci.com/gh/CivicTechTO/civictechto-scripts/edit#env-vars
    steps:
      - checkout

      - run: &decrypt_files
          name: decrypt files
          command: |
            openssl aes-256-cbc -k "$DECRYPTION_PASSWORD" -in service-key.json.enc -out service-key.json -d
      - restore_cache: &restore_cache
          keys:
          - cache-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - cache-

      - run: &install_dependencies
          name: install dependencies
          command: |
            pipenv sync --dev
      - save_cache: &save_cache
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  update_csv:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            wget http://opendata.toronto.ca/lobbyist/lobby.activity/lobbyactivity.zip
            unzip lobbyactivity.zip -d data
            pipenv run python cli.py parse-xml data/lobbyactivity-active.xml \
              --output-file data/communications.csv \
              --output-gsheet "https://docs.google.com/spreadsheets/d/1uCaEMd5jHKSaFwoLXhj06uB0AEca-hpK0Tr3E2jFTk8/edit"
